packages:
  - "packages/*"
allowBuilds:
  '@swc/core': true
  core-js: true
  core-js-pure: true
  esbuild: true
  keytar: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@storybook/addon-a11y@10.4.6'
  - '@storybook/builder-vite@10.4.6'
  - '@storybook/csf-plugin@10.4.6'
  - '@storybook/react-dom-shim@10.4.6'
  - '@storybook/react-vite@10.4.6'
  - '@storybook/react@10.4.6'
  - storybook@10.4.6
  - '@backstage/app-defaults@1.7.9'
  - '@backstage/catalog-client@1.16.0'
  - '@backstage/cli-defaults@0.1.3'
  - '@backstage/cli-module-actions@0.1.2'
  - '@backstage/cli-module-auth@0.1.3'
  - '@backstage/cli-module-build@0.1.4'
  - '@backstage/cli-module-config@0.1.3'
  - '@backstage/cli-module-github@0.1.3'
  - '@backstage/cli-module-info@0.1.3'
  - '@backstage/cli-module-lint@0.1.3'
  - '@backstage/cli-module-maintenance@0.1.3'
  - '@backstage/cli-module-migrate@0.1.3'
  - '@backstage/cli-module-new@0.1.4'
  - '@backstage/cli-module-test-jest@0.1.3'
  - '@backstage/cli-module-translations@0.1.3'
  - '@backstage/cli-node@0.3.3'
  - '@backstage/cli@0.36.3'
  - '@backstage/config-loader@1.10.12'
  - '@backstage/core-app-api@1.20.2'
  - '@backstage/core-compat-api@0.5.12'
  - '@backstage/core-components@0.18.11'
  - '@backstage/core-plugin-api@1.12.7'
  - '@backstage/dev-utils@1.1.24'
  - '@backstage/eslint-plugin@0.3.1'
  - '@backstage/frontend-plugin-api@0.17.2'
  - '@backstage/integration-react@1.2.19'
  - '@backstage/integration@2.0.3'
  - '@backstage/plugin-app-react@0.2.4'
  - '@backstage/plugin-catalog-react@3.1.0'
  - '@backstage/plugin-permission-react@0.5.2'
  - '@backstage/ui@0.16.0'
