#!/usr/bin/env bash
# Fetches the console-e2e-test Keycloak identity's credentials from the
# cluster's console-e2e-keycloak-creds Secret (kubernaut-system namespace)
# and caches them under $HOME — never in this repo/workspace, so they can
# never end up committed, `git grep`-able, or exposed by a workspace-relative
# script path.
#
# Usage (note: source it, don't execute it, so the exports land in your
# current shell):
#   source e2e/live/scripts/fetch-creds.sh
#   npx playwright test --config=playwright.live-v15.config.ts
#
# Re-run any time to refresh the cache (e.g. after the Secret rotates):
#   rm ~/.config/kubernaut-console-e2e/creds.env
#   source e2e/live/scripts/fetch-creds.sh
set -uo pipefail

STATE_DIR="${KUBERNAUT_E2E_STATE_DIR:-$HOME/.config/kubernaut-console-e2e}"
CREDS_FILE="$STATE_DIR/creds.env"

mkdir -p "$STATE_DIR"
chmod 700 "$STATE_DIR"

if [[ ! -f "$CREDS_FILE" ]]; then
  if ! command -v oc >/dev/null 2>&1; then
    echo "error: 'oc' not found on PATH" >&2
    return 1 2>/dev/null || exit 1
  fi
  echo "Fetching console-e2e-test Keycloak credentials from kubernaut-system..." >&2
  client_secret=$(oc get secret console-e2e-keycloak-creds -n kubernaut-system -o jsonpath='{.data.client-secret}' | base64 -d)
  password=$(oc get secret console-e2e-keycloak-creds -n kubernaut-system -o jsonpath='{.data.password}' | base64 -d)
  if [[ -z "$client_secret" || -z "$password" ]]; then
    echo "error: fetched empty credentials — check cluster access / Secret name" >&2
    return 1 2>/dev/null || exit 1
  fi
  ( umask 077
    cat > "$CREDS_FILE" <<EOF
# Generated by fetch-creds.sh on $(date -u +%FT%TZ). Contains real
# credentials for a dedicated, non-privileged test identity — never commit
# or copy this file into a git-tracked directory.
export LIVE_E2E_KEYCLOAK_CLIENT_SECRET='$client_secret'
export LIVE_E2E_KEYCLOAK_PASSWORD='$password'
EOF
  )
  chmod 600 "$CREDS_FILE"
  echo "Cached at $CREDS_FILE (outside the repo, mode 600)." >&2
else
  echo "Reusing cached credentials at $CREDS_FILE (rm it to force a refetch)." >&2
fi

# shellcheck disable=SC1090
source "$CREDS_FILE"
echo "LIVE_E2E_KEYCLOAK_CLIENT_SECRET / LIVE_E2E_KEYCLOAK_PASSWORD exported into this shell." >&2
