apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubernaut-console-plugin.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kubernaut-console-plugin.labels" . | nindent 4 }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ include "kubernaut-console-plugin.name" . }}-cert
spec:
  selector:
    {{- include "kubernaut-console-plugin.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      protocol: TCP
      port: {{ .Values.plugin.port }}
      targetPort: https
